In [1]:
!pip install pandas

In [2]:
!pip install -U ipykernel

  Attempting uninstall: ipykernel
    Found existing installation: ipykernel 6.5.0
    Uninstalling ipykernel-6.5.0:
      Successfully uninstalled ipykernel-6.5.0


In [3]:
import pandas as pd 
df= pd.read_csv("data.csv.csv")
df.head()

Unnamed: 0  acousticness  danceability  duration_ms  energy  \
0          0        0.0102         0.833     204600.0   0.434   
1          1        0.1990         0.743     326933.0   0.359   
2          2        0.0344         0.838     185707.0   0.412   
3          3        0.6040         0.494     199413.0   0.338   
4          4        0.1800         0.678     392893.0   0.561   

   instrumentalness  key  liveness  loudness  mode  speechiness    tempo  \
0          0.021900  2.0    0.1650    -8.795   1.0       0.4310  150.062   
1          0.006110  1.0    0.1370   -10.401   1.0       0.0794  160.083   
2          0.000234  2.0    0.1590    -7.148   1.0       0.2890   75.044   
3          0.510000  5.0    0.0922   -15.236   1.0       0.0261   86.468   
4          0.512000  5.0    0.4390   -11.648   0.0       0.0694  174.004   

   time_signature  valence  target      song_title            artist;  
0             4.0    0.286     1.0        Mask Off            Future;  
1             4.0    0.588     1.0         Redbone  Childish Gambino;  
2             4.0    0.173     1.0    Xanny Family            Future;  
3             4.0    0.230     1.0  Master Of None       Beach House;  
4             4.0    0.904     1.0  Parallel Lines       Junior Boys;

In [4]:
import numpy as np
new_rok=df['acousticness'].to_numpy()
new_dzas=df["danceability"].to_numpy()
pop=df["duration_ms"].to_numpy()
new_pop=np.array([])
okay=0
error=0
for element in pop:
    element=str(element)
    element=element[:-2]
    #print(element)
    try:
        element=int(float(element))
        #print(element)
        new_pop=np.append(new_pop,element)
        #print("Все норм")
        okay+=1
    except ValueError:
        #print("Ошибка")
        error+=1
#print(new_pop)
#print(new_dzas)
#print(new_rok)
print("Все норм в ",okay," случаях")
print("Ошибка в ",error," случаях")
print(new_pop[0:5])
print(new_rok[0:5])
print(new_dzas[0:5])

Все норм в  1949  случаях
Ошибка в  68  случаях
[204600. 326933. 185707. 199413. 392893.]
[0.0102 0.199  0.0344 0.604  0.18  ]
[0.833 0.743 0.838 0.494 0.678]


In [14]:
import pandas as pd 
import random
df= pd.read_csv("data.csv.csv")
df.head()



import numpy as np
new_rok=df['acousticness'].to_numpy()
new_dzas=df["danceability"].to_numpy()
pop=df["duration_ms"].to_numpy()
new_pop=np.array([])
okay=0
error=0
for element in pop:
    element=str(element)
    element=element[:-2]
    try:
        element=int(float(element))
        new_pop=np.append(new_pop,element)
        okay+=1
    except ValueError:
        error+=1
#print("Все норм в ",okay," случаях")
#print("Ошибка в ",error," случаях")
#print(new_pop[0:5])
#print(new_rok[0:5])
#print(new_dzas[0:5])




import math
df.index.name="Index column"
rasstoyaniye=np.array([])
def scaling(massive):
    max=0
    for element in massive:
        if element>max:
            max=element
    min=max
    for element in massive:
        if element<min:
            min=element
    range=max-min
    i=0
    for element in massive:
        massive[i]=massive[i]-min
        massive[i]=massive[i]/range
        i+=1

scaling(new_rok)
scaling(new_pop)
scaling(new_dzas)

our_user_data=np.array([])
i = df.index.get_loc(3)
our_user_data=df.iloc[i]
our_user_data=our_user_data[1:4]
our_user_data=our_user_data.to_numpy()


def rasstoyaniye(masive1,massive2,massive3):
    rasstoyaniye_massive=np.array([]) 
    for element in new_pop:
        try:
            index_elementa=np.where(massive3 == element)
            calculations=math.sqrt((our_user_data[0]-masive1[index_elementa])**2+(our_user_data[1]-massive2[index_elementa])**2+(our_user_data[2]-massive3[index_elementa])**2)
            rasstoyaniye_massive= np.append(rasstoyaniye_massive,calculations)
        except TypeError:
            continue

    k_nearest_neighbours=np.array([])
    k_nearest_neighbours=np.array([random.randint(100000000000,100000000000000000000) for i in range(4)])
    #print(k_nearest_neighbours)
    k_nearest_neighbours_indexes=np.array([random.randint(100000000000,100000000000000000000) for i in range(4)])
    for element in rasstoyaniye_massive:
        #нужно получить массив индексов
        massive_indexov_posle_sortirovki=np.argsort(k_nearest_neighbours)
        k_nearest_neighbours=np.sort(k_nearest_neighbours)
        #теперь нужно поставить индексы на правильные места, для соответсвия значениям
        counter_of_indexes=0
        for correct_index in massive_indexov_posle_sortirovki:
            index_of_element_on_this_place=massive_indexov_posle_sortirovki[counter_of_indexes]
            k_nearest_neighbours_indexes[counter_of_indexes]=k_nearest_neighbours_indexes[index_of_element_on_this_place]
            counter_of_indexes+=1
        max_for_k_nearest_neighbours=k_nearest_neighbours[-1]
        if element<max_for_k_nearest_neighbours and element!=k_nearest_neighbours[0] and element!=k_nearest_neighbours[1] and element!=k_nearest_neighbours[2] and element!=k_nearest_neighbours[3]:
            for value in k_nearest_neighbours:
                index_elementa=np.where(k_nearest_neighbours == value)
                print(index_elementa,"Это индекс элемента")
                if element<value:
                    k_nearest_neighbours[index_elementa]=element
                    indexik_elementa=np.where(rasstoyaniye_massive == element)
                    k_nearest_neighbours_indexes[index_elementa]=indexik_elementa
                    break
    #print(rasstoyaniye_massive)
    print(k_nearest_neighbours,"-это расстояния между 4 ближайшеми соседями")
    print(k_nearest_neighbours_indexes,"-это индексы 4 ближайших к пользователю соседей в таблице")
rasstoyaniye(new_rok,new_dzas, new_pop)



(array([0], dtype=int64),) Это индекс элемента
(array([0], dtype=int64),) Это индекс элемента
(array([1], dtype=int64),) Это индекс элемента
(array([0], dtype=int64),) Это индекс элемента
(array([1], dtype=int64),) Это индекс элемента
(array([0], dtype=int64),) Это индекс элемента
(array([0], dtype=int64),) Это индекс элемента
(array([1], dtype=int64),) Это индекс элемента
(array([0], dtype=int64),) Это индекс элемента
(array([1], dtype=int64),) Это индекс элемента
(array([0], dtype=int64),) Это индекс элемента
(array([1], dtype=int64),) Это индекс элемента
(array([2], dtype=int64),) Это индекс элемента
(array([0], dtype=int64),) Это индекс элемента
(array([1], dtype=int64),) Это индекс элемента
(array([0], dtype=int64),) Это индекс элемента
(array([1], dtype=int64),) Это индекс элемента
(array([2], dtype=int64),) Это индекс элемента
(array([0], dtype=int64),) Это индекс элемента
(array([1], dtype=int64),) Это индекс элемента
(array([2], dtype=int64),) Это индекс элемента
(array([0], d

In [22]:
df_for_applying= pd.read_csv("data_for_music_application_applying_correct.csv")
df_for_applying

Names Rock and roll  Dzas   Pop
0      Susan             4   7.0   3.0
1       Jack             5   6.0   0.0
2       Jiry             8   2.0   3.0
3     Danylo            10  10.0  10.0
4     Andrew             5  10.0   5.0
5      Illya             2   8.0   3.0
6      Mikle            10   2.0   6.0
7      Ayzak         4;0;2   NaN   NaN
8       John             6  10.0   2.0
9      Joana             2   5.0  10.0
10     Shina            10   1.0   2.0
11     Jason             6   4.0   4.0
12     Kolum             2   5.0   7.0
13      Paul             1   4.0  10.0
14  Our user           NaN   NaN   NaN
15      Karl             8   3.0   4.0