In [32]:
import pandas as pd
df_for_applying= pd.read_csv("data_for_music_application_applying_correct.csv")
df_for_applying

Names  Rock and roll  Dzas  Pop
0    Susan              4     7    3
1     Jack              5     6    0
2     Jiry              8     2    3
3   Danylo             10    10   10
4   Andrew              5    10    5
5    Illya              2     8    3
6    Mikle             10     2    6
7    Ayzak              4     0    2
8     John              6    10    2
9    Joana              2     5   10
10   Shina             10     1    2
11   Jason              6     4    4
12   Kolum              2     5    7
13    Paul              1     4   10
14    Karl              8     3    4

In [3]:
!pip install pandas
!pip install -U ipykernel

In [144]:
import pandas as pd 
df= pd.read_csv("data_for_music_application_applying_correct.csv")
df

Names  Rock and roll  Dzas  Pop
0    Susan              4     7    3
1     Jack              5     6    0
2     Jiry              8     2    3
3   Danylo             10    10   10
4   Andrew              5    10    5
5    Illya              2     8    3
6    Mikle             10     2    6
7    Ayzak              4     0    2
8     John              6    10    2
9    Joana              2     5   10
10   Shina             10     1    2
11   Jason              6     4    4
12   Kolum              2     5    7
13    Paul              1     4   10
14    Karl              8     3    4

In [145]:
import numpy as np
rok=df["Rock and roll"].to_numpy()
dzas=df["Dzas"].to_numpy()
pop=df["Pop"].to_numpy()
rok=rok.astype(float)
dzas=dzas.astype(float)
pop=pop.astype(float)
print(pop)
print(rok)
print(dzas)
df
type(rok)

[ 3.  0.  3. 10.  5.  3.  6.  2.  2. 10.  2.  4.  7. 10.  4.]
[ 4.  5.  8. 10.  5.  2. 10.  4.  6.  2. 10.  6.  2.  1.  8.]
[ 7.  6.  2. 10. 10.  8.  2.  0. 10.  5.  1.  4.  5.  4.  3.]


numpy.ndarray

In [120]:
#запускать эту ячейку, только если хотите маштабировать значения от 0 до 1
import math
#df.index.name="Index column"
def scaling(massive):
    max=-1
    for element in massive:
        if element>max:
            max=element
    #print(max)
    min=max
    for element in massive:
        if element<min:
            min=element
    #print(min)
    range=max-min
    #print(range)
    i=0
    for element in massive:
        element_in_range=massive[i]-min
        #print(element_in_range/range)
        massive[i]=element_in_range/range
        i+=1
    print(massive,"-array")
    return massive
scaling(rok)
scaling(pop)
scaling(dzas)
df

[0.33333333 0.44444444 0.77777778 1.         0.44444444 0.11111111
 1.         0.33333333 0.55555556 0.11111111 1.         0.55555556
 0.11111111 0.         0.77777778] -array
[0.3 0.  0.3 1.  0.5 0.3 0.6 0.2 0.2 1.  0.2 0.4 0.7 1.  0.4] -array
[0.7 0.6 0.2 1.  1.  0.8 0.2 0.  1.  0.5 0.1 0.4 0.5 0.4 0.3] -array


Names  Rock and roll  Dzas  Pop
0    Susan              4     7    3
1     Jack              5     6    0
2     Jiry              8     2    3
3   Danylo             10    10   10
4   Andrew              5    10    5
5    Illya              2     8    3
6    Mikle             10     2    6
7    Ayzak              4     0    2
8     John              6    10    2
9    Joana              2     5   10
10   Shina             10     1    2
11   Jason              6     4    4
12   Kolum              2     5    7
13    Paul              1     4   10
14    Karl              8     3    4

In [146]:
our_user_data=np.array([])
our_user_data=df[14:15]
our_user_data=our_user_data.to_numpy()
our_user_data.reshape(1, our_user_data.shape[0]*our_user_data.shape[1])
print(our_user_data)
odnumerniy_massive=np.array([])
for stroka in our_user_data:
    for chislo in stroka:
        if type(chislo)==int:
            odnumerniy_massive=np.append(odnumerniy_massive,chislo)
our_user_data=odnumerniy_massive 
#our_user_data=scaling(our_user_data)          
print(our_user_data)

[['Karl' 8 3 4]]
[8. 3. 4.]


In [147]:
import random
def rasstoyaniye(masive1,massive2,massive3):
    rasstoyaniye_massive=np.array([]) 
    index_elementa=0
    for element in pop:
        try:
            calculations=math.sqrt((our_user_data[0]-masive1[index_elementa])**2+(our_user_data[1]-massive2[index_elementa])**2+(our_user_data[2]-massive3[index_elementa])**2)
            rasstoyaniye_massive= np.append(rasstoyaniye_massive,calculations)
        except TypeError:
            print("TypeError")
            continue
        index_elementa+=1
    print(rasstoyaniye_massive)
    k_nearest_neighbours_indexes=np.array([])
    massive_indexov_posle_sortirovki=np.argsort(rasstoyaniye_massive[:-2])
    rasstoyaniye_massive=np.sort(rasstoyaniye_massive)
    massive_indexov_posle_sortirovki=massive_indexov_posle_sortirovki[:4]
    #print(rasstoyaniye_massive)
    for index in massive_indexov_posle_sortirovki:
        k_nearest_neighbours_indexes=np.append(k_nearest_neighbours_indexes,index)
        print(index)
    print(k_nearest_neighbours_indexes,"-это индексы 4 ближайших к пользователю соседей в таблице")
rasstoyaniye(rok,dzas, pop)


[5.74456265 5.83095189 1.41421356 9.43398113 7.68114575 7.87400787
 3.         5.38516481 7.54983444 8.71779789 3.46410162 2.23606798
 7.         9.2736185  0.        ]
2
11
6
10
[ 2. 11.  6. 10.] -это индексы 4 ближайших к пользователю соседей в таблице


In [69]:
a=0.1
print(float(a))

0.1
